# Site settings
title: Daily Bruin | Graduation 2014
email: online@media.ucla.edu
description: "Daily Bruin UCLA 2014 Graduation Issue, featuring the issue's annual -30- columns and the year's roundup in News, Sports, A&E, Video, and Radio "
baseurl: ""
url: "http://graphics.dailybruin.com/grad2014/"

# Build settings
markdown: kramdown
permalink: pretty
